### ISSUE TITLE
Issues/Suggestions - Brain Atlas - Mite

### ISSUE THREAD

**Issue by mitemijalkov** [softmatterlab/BRAPH-2-Matlab#1056]
The following are issues that I have encountered while running Brain Atlas. There are both minor and major issues, therefore I create this checklist instead of opening multiple issues:

- [x] (1) Minor: I have noticed that the table showing the brain atlas resets to the top after every change.

- [x] (2) Lets say that a brain surface is plotted. If one tries to plot another surface, a blank figure appears. The surface is not changed, so the original surface is plotted in the new figure, the old figure remains blank.  
However, if the figure where the surface is plotted is closed, a new surface can be plotted correctly.

- [x] (3) I think it is better to use the ICBM 152 plot for the default surface. The currently used "human" surface is a bit weird and I think it is made to emphasize the subcortical volumes. I also think that the default plot of the brain should be in single color.  - Anna

- [x] (4) If a brain figure is closed and the surface is replotted, the surface is replotted with the last parameters but the drop down menus are on the default values - what is plotted and what is shown does not correspond to each other.

- [x] (5) When the brain view is changed, the changes in the surface are not preserved. For example, if the color of the brain is red, after changing the view, the color becomes colormap.

- [x] (6) It also seems that changing the view reverts plotting options back to defaults (in terms of lighting options). The dropdown list remain on the same item, but the whole scene changes.

- [x] (7) The zoom in/out, hand and rotate buttons on our panel do not work. The default in Matlab do work. If by chance both are selected, the tollbar icons of Matlab specify which operations will be done.

- [x] (8) Atlas in json format cannot be imported.

- [x] (9) Minor, when importing atlas from txt: Even though I had an atlas of 68 regions, while loading, the progress bar was showing that 408 regions are loaded. The final result is an atlas with 68 regions. (COMMAND LINE?) 

- [x] (10) In this version, it is not possible to start the analysis with anything else other than brain atlas in excel format.

- [x] (11) There is something weird going on with the xls upload and this is an issue that I cannot reproduce constantly. If I close the BRAPH file there is problem sometimes, such that an error appeared when I tried to load from xls file. Then I restart Matlab, start BRAPH again and no problem appears.
- Update on this issue - I am now able to reproduce it. If Braph GUI is closed and I run clear all and close all on the command line, then after running BRAPH2GUI without closing Matlab I cannot again upload the brain atlas.

**Comment by giovannivolpe** [comment]
@egolol @mitemijalkov can you check these issues  together?
