### ISSUE TITLE
Add function that regresses out the effect of covariant

### ISSUE THREAD

**Issue by c-yuwei** [softmatterlab/BRAPH-2-Matlab#1179]
Add function that regresses out the covariant effect (e.g. gender or age) from the target, such as calculated graph measures.

**Comment by giovannivolpe** [comment]
A few quesrtions:
- why do we need it?
- isn't it already implemented in the relevant analyses?
- also, if needed, shouldn't it be implemented as an element, so it can be used in the pipelines?

**Comment by c-yuwei** [comment]
we dont have that in braph2.
What anna did is for structural data, so the sex and age are accounted in the correlation as the covariate.
What this PR is for fMRI and DTI per se, regressing the effect of covariate from the calculated measure.

Discussion:

Implement it as an element or in AnalyzeEnsemble

> A few quesrtions:
> 
> * why do we need it?
> * isn't it already implemented in the relevant analyses?
> * also, if needed, shouldn't it be implemented as an element, so it can be used in the pipelines?

**Comment by c-yuwei** [comment]
Discussion:

The current implementation only regresses out the covariates of age and sex. And there is no flexibility to choose which one.
People might want to introduce more than 2 covariates, and even decide which ones to be regressing out.
There should be an option, composed of the available covariates, and users can choose which ones to be regressing out.

**Comment by c-yuwei** [comment]
Create the option already 

- [ ] age
- [ ] sex
- [ ] both

**Comment by c-yuwei** [comment]
https://github.com/softmatterlab/Braph-2.0-Matlab/issues/1207

> Discussion for future reference:
> 
> The current implementation only regresses out the covariates of age and sex. There is no flexibility to choose which one. People might want to introduce more than 2 covariates, and even decide which ones to be regressed out. There should be an option, composed of the available covariates, and users can choose which ones to be regressing out. For example:
> 
> * [ ]  age
> * [ ]  sex
> * [ ]  MMSE
> 
> In order to do that, we have to re-discuss the structure of object SUBJECT and IMPORTER.

https://github.com/softmatterlab/Braph-2.0-Matlab/issues/1207

**Comment by c-yuwei** [comment]
Chang of solution design #1380
