### ISSUE TITLE
Pipelines alpha test

### ISSUE THREAD

**Issue by c-yuwei** [softmatterlab/BRAPH-2-Matlab#1243]
- [ ] FUN **(ready for test)**
- [ ] CON **(ready for test)**
- [ ] ST **(ready for test)**
- [ ] FUN CON MP
- [ ] ST MP

Please note to test "ALL" of the measures, making sure they are calculated correctly.
Bugs should be reported here, and well described how to replicate the error or bugs

**Comment by annacanal** [comment]
<img width="284" alt="Screenshot 2022-03-21 at 11 07 25" src="https://user-images.githubusercontent.com/31701548/159240616-08a60c5a-3a1a-4ebd-87dd-db2cffb1ce21.png">
When calculating a nodal measure, the button "plot brain view" appears on top of the table. Tested that both in MAC and ubuntu and it is the same. I tested with the analysis ST_WU (which before this button was not overlapping with the table data)

**Comment by annacanal** [comment]
The button to select which region results to plot (nodal measure in threshold analysis) is under the line button in ubuntu
![image](https://user-images.githubusercontent.com/31701548/159273077-b3bcec52-fb6d-44d0-92b9-cf928ebad0a1.png)

![image](https://user-images.githubusercontent.com/31701548/159273261-9d32cf72-8fd4-4330-9949-010dc73d5e2d.png)

**Comment by annacanal** [comment]
> The button to select which region results to plot (nodal measure in threshold analysis) is under the line button in ubuntu and MAC (This was analysis_ST_BUT) ![image](https://user-images.githubusercontent.com/31701548/159273992-00dac0e7-9bf7-4024-8f3e-3f1da8f844c7.png)
> 
> ![image](https://user-images.githubusercontent.com/31701548/159273077-b3bcec52-fb6d-44d0-92b9-cf928ebad0a1.png)
> 
> ![image](https://user-images.githubusercontent.com/31701548/159273261-9d32cf72-8fd4-4330-9949-010dc73d5e2d.png)

Make bigger the button showing the name of the measure, make bigger the left side, there is a lot of empty space on the right:
<img width="865" alt="Screenshot 2022-03-21 at 14 42 21" src="https://user-images.githubusercontent.com/31701548/159275798-a2cf70b3-85e3-423d-b468-a378f23c0c5f.png">

**Comment by egolol** [comment]
Solved

**Comment by annacanal** [comment]
> <img alt="Screenshot 2022-03-21 at 11 07 25" width="284" src="https://user-images.githubusercontent.com/31701548/159240616-08a60c5a-3a1a-4ebd-87dd-db2cffb1ce21.png">
> 
> When calculating a nodal measure, the button "plot brain view" appears on top of the table. Tested that both in MAC and ubuntu and it is the same. I tested with the analysis ST_WU (which before this button was not overlapping with the table data)

I saw this is solved now
