### ISSUE TITLE
NN GUI preparation in general

### ISSUE THREAD

**Issue by c-yuwei** [softmatterlab/BRAPH-2-Matlab#1275]
This issue aims to provide first version of NN GUI, with CON WU Classification as an example.

- [x] Layout changes (naming panels, hiding unecessary properties)
- [x] Open new windows next to old one
Make sure it applies to all NNGroup and figures
- [x] Hide / Show
Make sure it applies to all NNGroup and figures (i.e. NNEvaluator or so)
- [x] Measure table (disable when INPUT TYPE is not graph measures, also remove the space)
![image](https://user-images.githubusercontent.com/30530538/160851849-72a298bb-a381-43fa-afa7-dc41fee1bee8.png)
- [x] NN layers plot docking
- [x] NN training progress docking
- [x] NN AUC docking
only show the first column
- [x] NN Confusion matrix docking
- [x] feature mask lock warning

<img width="724" alt="image" src="https://user-images.githubusercontent.com/30530538/161716347-acb3be33-6fb3-4bc4-b02b-42bdc7a4cbc2.png">

- [x] represent the scalar as a string or something (like densities for BUD)
Properties: split for gr1, split for gr2, feature mask, layers, 
<img width="182" alt="image" src="https://user-images.githubusercontent.com/30530538/161721402-0f463097-7c10-4313-a745-d8d92932af11.png">

- [x] Compatible graph measures check
- [x] mess up when deleting the properties
model, auc (only happened in plotPropCell)
<img width="167" alt="image" src="https://user-images.githubusercontent.com/30530538/161723025-f8eb446a-9668-4177-ad60-0acee4f7b830.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/30530538/162067228-2093a2f6-09a2-444b-9d0c-2e9b0d40328b.png">

************** final steps **************
- [x] brain viewer for feature importance visualization in cross-validation (only for adj and structural input)
- [x] properly present the input for a subject in terms of adj or graph measures or structural data

**Comment by egolol** [comment]
NN training progress docking this cant be done
