### ISSUE TITLE
PlotBrainView errors

### ISSUE THREAD

**Issue by annacanal** [softmatterlab/BRAPH-2-Matlab#1277]
In **Comparison ST_WU**, when I want to show the results of the comparison **by pressing Symbol size**, it jumps to this error:

```
Error using PlotBrainGraphComparison.checkProp (line 1058)
BRAPH2:PlotBrainGraphComparison:WrongInput The value num[1 68] [ 11            2           13            4            1           10          0.1         ... is not a valid property syms_size (nc).

Error in Element/set (line 657)
                            el.checkProp(prop, value) % check value format

Error in PlotBrainGraphComparison/getMCRPanel/update_brain_meas_plot (line 3202)
		                    pl.set('SYMS_SIZE', size_');

Error in PlotBrainGraphComparison/getMCRPanel/cb_checkbox_meas_symbolsize (line 3101)
		                update_brain_meas_plot()
 
Error while evaluating UIControl Callback.
```

**Sphere radius** works. But I think it just **plots the positive differences and not the negative.** Shouldn't it plot the absolute value of the difference?
![Screenshot 2022-03-31 at 16 51 43](https://user-images.githubusercontent.com/31701548/161085178-f9aa5118-2556-4b91-9041-c6c19caa7064.png)

**Comment by egolol** [comment]
It used to be a lower limit of zero. I can change it to abs, just convince Giovanni.

**Comment by annacanal** [comment]
Same error as in ST_WU, happens in **ST_BUD comparison**, when pressing the **Symbol Size**:

```
Error using PlotBrainGraphComparison.checkProp (line 1058)
BRAPH2:PlotBrainGraphComparison:WrongInput The value num[1 68] [ 1           3           7         0.1           1         0.1           2         0.1    ... is not a valid
property syms_size (nc).

Error in Element/set (line 657)
                            el.checkProp(prop, value) % check value format

Error in PlotBrainGraphComparison/getMCRPanel/update_brain_meas_plot (line 3202)
		                    pl.set('SYMS_SIZE', size_');

Error in PlotBrainGraphComparison/getMCRPanel/cb_checkbox_meas_symbolsize (line 3101)
		                update_brain_meas_plot()
 
Error while evaluating UIControl Callback.
```

**Comment by annacanal** [comment]
In Analysis functional multiplex WU, in the PlotBrainView of a nodal unilayer measure, once I check the value size, the numbers appears for one layer, when I change to the next layer, more numbers appear but the previous don't disappear. Finally, moving to layer 3, there are many numbers corresponding to the regions' values of the 3 layers:

![Screenshot 2022-04-01 at 11 09 11](https://user-images.githubusercontent.com/31701548/161232915-60dfaa94-328c-4cd8-a3f6-a36d6d4f193a.png)

![Screenshot 2022-04-01 at 11 09 24](https://user-images.githubusercontent.com/31701548/161233010-0e1b5029-9dde-4ed9-a88a-ec0a4e34e3aa.png)

![Screenshot 2022-04-01 at 11 09 33](https://user-images.githubusercontent.com/31701548/161233056-2fd8fba5-3bf7-4b3e-bb41-e76902f35469.png)

**Comment by annacanal** [comment]
Also in the **nodal unilayer measure in functional multiplex WU**, the Table in the measure results is larger and starts higher and then the plotbrainview button is on top of the table:
![Screenshot 2022-04-01 at 11 04 51](https://user-images.githubusercontent.com/31701548/161234187-4295e7b5-1474-44fb-bccb-cbe2fc4a421d.png)
d

**Comment by annacanal** [comment]
In the **PlotBrainView of nodal superglobal measures**, the **layers button should not be there**, since there is jsut one results for all layers:

![Screenshot 2022-04-01 at 11 25 26](https://user-images.githubusercontent.com/31701548/161235802-61e76762-169b-43f5-b7fc-b925a312e505.png)

**Comment by annacanal** [comment]
In **Comparison Functional Multiplex WU**, the measure results table of a **nodal unilayer measure** has two bars:

![Screenshot 2022-04-01 at 11 34 06](https://user-images.githubusercontent.com/31701548/161237322-f6f312ca-8722-4d2a-a356-b7e6ee16f9ac.png)

**Comment by annacanal** [comment]
After opening the Plot Brain View window, this _layer 1_ tag appears on top of the tables, in both **nodal unilayer and nodal superglobal measures**:
![Screenshot 2022-04-01 at 11 41 15](https://user-images.githubusercontent.com/31701548/161238597-d7b38032-7241-47c9-8403-85b8547973e0.png)

**Comment by annacanal** [comment]
The bar titles are interchanged, the upper one is changing the density and the lower one is changing the multiplex layer:
In thats sense, on the left, we have a nodal superglobal measure, and when i move the density bar, which in reality is layer, an error jumps since there is just on result per all layers:

![Screenshot 2022-04-01 at 11 58 45](https://user-images.githubusercontent.com/31701548/161241613-67a50325-d216-4c19-b56b-96a00de07710.png)


```
Index exceeds the number of array elements (2).

Error in PlotPropMeasureNodalMultilayer/update (line 850)
		                'Data', value{correct_i}, ...

Error in PlotPropMeasureNodalMultilayer/draw/cb_slider_layer (line 773)
		            pr.update()
 
Error while evaluating UIControl Callback.
```

**Comment by egolol** [comment]
solved
