### ISSUE TITLE
Main GUI

### ISSUE THREAD

**Issue by annacanal** [softmatterlab/BRAPH-2-Matlab#1332]
Main GUI/ landing GUI after running **braph2**. The logo is shrunk, this was solved months ago, so something happened:

![Screenshot 2022-04-19 at 09 34 45](https://user-images.githubusercontent.com/31701548/163976286-8fadd1a7-e586-492a-b8fc-6ba4d5c39763.png)

**Comment by egolol** [comment]
I was told to not resize.
