### ISSUE TITLE
Bug report on Nodal Degree

### ISSUE THREAD

**Issue by mitemijalkov** [softmatterlab/BRAPH-2-Matlab#1377]
**Describe the bug**
For an atlas of 68 nodes, the nodal degree for a given node is 68 at density of 100%.

**To Reproduce**
The bug appears on connectivity pipeline BUD analysis with connectivity example data (group 1).

**Expected behavior**
The degree should be 67 since the self-connections should be eliminated.

**Comment by giovannivolpe** [comment]
I've corrected this. It was a problem with binarize, only occurring for density 100%, so not urgent and can be corrected with the PR associated to issue #1272
