### ISSUE TITLE
N number of covariates and correlates

### ISSUE THREAD

**Issue by annacanal** [softmatterlab/BRAPH-2-Matlab#1380]
**Describe the solution you'd like**
Allow the use of a flexible number of covariates&correlates.

**Describe alternatives you've considered**
Add a dictionary in Subject or Group with the **value** of this dependent data, a column for **covariate/no covariate**, and another column for **correlate/no correlate**.

**Comment by giovannivolpe** [comment]
This will be taken care of in issue #1391
