### ISSUE TITLE
Changing Labels Brain Atlas GUI

### ISSUE THREAD

**Issue by Joana70** [softmatterlab/BRAPH-2-Matlab#1387]
I got the following error when I was changing the font size of a label of a specific region and didn't do it fast enough so the software assigned it a NaN:

Error using SettingsText.checkProp (line 880)
BRAPH2:SettingsText:WrongInput The value NaN is not a valid property fontsize
(mw).

Error in Element/set (line 731)
                                    el.checkProp(prop, value) % check value format

Error in PanelPropIDictTable/cb_table_edit/cb_table_edit_default (line 1544)
		                    dict.getItem(i).set(col, newdata)

Error in PanelPropIDictTable/cb_table_edit (line 1475)
		        cb_table_edit_default()

Error in PanelPropIDictTable/draw/cb_table_edit (line 1112)
		            pr.cb_table_edit(event.Indices(1),
                            cols(event.Indices(2)), event.NewData)
 
Error using matlab.ui.internal.controller.uitable.WebMWTableController/fireCallbacksFromCellEdit (line 791)
Error while evaluating Table CellEditCallback.

**Comment by giovannivolpe** [comment]
Ok, this will be solved together in PR #1389
