### ISSUE TITLE
Comparison error due to lack of covariates 

### ISSUE THREAD

**Issue by c-yuwei** [softmatterlab/BRAPH-2-Matlab#1418]
**Describe the bug**
The comparison with covariates doesn't work for functional pipelines.

**To Reproduce**
1. Go to 'Pipeline Functional Comparison BUD'
2. Click on 'Group 1 Analysis'
3. Set 'CORRELATION RULE' to 'Pearson with covariates'
4. Click on 'Group Comparison'
5. Scroll down to 'ENSEMBLE COMPARISONS' and calculate any measure
6. See error

**Expected behavior**
An error happens in Command Window:

Not enough input arguments.

Error in Correlation.getAdjacencyMatrix (line 82)
                    [A, P] = partialcorr(data, covariates, 'Type', 'Pearson');

Error in AnalyzeEnsemble_FUN_BUD/calculateValue (line 972)
					    A = Correlation.getAdjacencyMatrix(data, a.get('CORRELATION_RULE'), a.get('NEGATIVE_WEIGHT_RULE'));

Error in Element/get (line 922)
                        value = el.calculateValue(prop);

Error in Element/memorize (line 968)
                value = el.get(prop); % retrieves or calculates the value

Error in ComparisonEnsemble/calculate_results (line 1099)
		    ms1 = cellfun(@(x) x.getMeasure(measure_class, varargin{:}).memorize('M'), c.get('A1').memorize('G_DICT').getItems, 'UniformOutput', false);

Error in ComparisonEnsemble/calculateValue (line 1018)
					    [cp.diff, cp.p1, cp.p2, cp.ci_lower, cp.ci_upper] = calculate_results(cp);

Error in Element/get (line 922)
                        value = el.calculateValue(prop);

Error in Element/memorize (line 968)
                value = el.get(prop); % retrieves or calculates the value

Error in PPCompareEnsemble_CpDict/cb_comparison_calculate (line 1091)
		                el.getComparison(measure).memorize('DIFF');

Error in PPCompareEnsemble_CpDict/draw/cb_comparison_calculate (line 878)
		        pr.cb_comparison_calculate()
 
Error using matlab.ui.internal.controller.WebMenuController/fireActionEvent
Error while evaluating Menu Callback.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by egolol** [comment]
solved in another issue
