### ISSUE TITLE
some questions about the measures calculation of weighted directed graphs

### ISSUE THREAD

**Issue by smile0227** [softmatterlab/BRAPH-2-Matlab#1522]
Dear Braph Community,
I am sorry to bother you. 
I have been troubled by the measures calculation of weighted directed graphs for a long time, until I recently discovered that Braph 2.0.0.a3 was released. I really appreciate your team's effort. 
I've calculated the weighted connectivity matrix, and it seems that I can calculate the graph topological properties by choosing _**Pipeline Connectivity Analysis WD**_.
However, I am not familiar with the operation process, including the setting of some parameters and their meaning. 
For example, how _**ID,label, etc.**_ should be set in the image below. Where are the results stored, and how can I extract them for further statistical analysis?
Is there are any tutorials I can refer to? 
![image](https://user-images.githubusercontent.com/71267915/208588989-ccb509d1-59a6-4f43-9858-1244011ca4be.png)
Looking forward to your reply.
Yours,
Yanxi

**Comment by egolol** [comment]
Hi @smile0227 thank you for using BRAPH 2, sorry for the long wait on our reply as we were on winter break. You can read our tutorials on our website www.braph.org. As for extracting the data, you can import to a '.json' and retrieve the information there or right-click over the table that shows the measure and select export to '.xls'. 
edit: I will add that you can read the script that shows command-line usage of BRAPH 2 of the corresponding pipeline: 'example_CON_WD'.
