### ISSUE TITLE
Multiplex connectivity analyze with "structural volume" and "DTI data" 

### ISSUE THREAD

**Issue by smilepkm** [softmatterlab/BRAPH-2-Matlab#1531]
Hello, 
First of all, thank you very much to the developers of braph.

There is one question. 
I want to conduct a multilayer network analysis with structural volume and DTI data. 
What pipeline should I choose? 
I searched about it and couldn't seem to find anything suitable.
Thank you for your help.

**Comment by egolol** [comment]
Hi @smilepkm,

Thank you for using BRAPH 2. The answer you seek is to use the Pipeline Connectivity Multiplex. This will allow you to utilize the pre-calculated structural volume as input and import it into that Pipeline. If you want to do a group network for structural volume,  you will need to use the Pipeline Connectivity Multiplex Group Average. Please utilize our tutorial section [tutorial](https://github.com/braph-software/BRAPH-2/tree/develop/tutorials).

Best,
Emiliano
