### ISSUE TITLE
Failed in importing group .xlsx when the number of the row exceeds the number of the column.

### ISSUE THREAD

**Issue by caopeiyu1998** [softmatterlab/BRAPH-2-Matlab#1547]
**Describe the bug**
When I am using the pipeline structure comparison BUT with BRAPH 2.00 a4，I used the desikan subcortical atlas, and my two groups contained 72 subjects, respectively. The features i used were volumes of 68 subcortical regions. Thus, the group .xlsx contains 71 columns and 73 rows. When I imported the group .xlsx, a dialog box jumped out showing: "Index in position 2 exceeds array bounds. Index must not exceed 71", and when I deleted several subjects to control the rows less than 71, the .xlsx could be imported successfully. It seems that the number of the row can not exceed the number of the column.

**Expected behavior**
How to fix this bug.

**Screenshots**
![image](https://github.com/softmatterlab/BRAPH-2-Matlab/assets/86464210/e80a177e-b06d-43f3-af67-854b0a057e0f)
![image](https://github.com/softmatterlab/BRAPH-2-Matlab/assets/86464210/426e65fa-2c24-4aa6-b58b-efee7d83feac)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS

**Comment by giovannivolpe** [comment]
@caopeiyu1998 We have now released a new version of BRAPh 2 that should address also this issue.
Please, let us know if the issue persists.
