### ISSUE TITLE
ROC plot error under  Pipeline Classification Cross-Validation Connectivity BUD Measure

### ISSUE THREAD

**Issue by hanzh346** [softmatterlab/BRAPH-2-Matlab#1652]
The error raised when running pipeline **Classification Cross-Validation Connectivity BUD Measure**. The error is produced when calaulating measure "**Clustering**" then In step 4. ploting **ROC** plot after training the NN.
 
![image](https://github.com/braph-software/BRAPH-2/assets/80827495/c3a83a4d-8b79-4e5f-97fd-6e20f7de7101)

![image](https://github.com/braph-software/BRAPH-2/assets/80827495/ae69f626-8a58-44d1-afc5-18c352ed8310)

**Comment by iok-ui** [comment]
This is solved by this PR https://github.com/braph-software/BRAPH-2/pull/1735
