### ISSUE TITLE
Error for exporting SmallWorldness to XLS

### ISSUE THREAD

**Issue by zhileixu** [softmatterlab/BRAPH-2-Matlab#1679]
**Describe the bug**
When I tried to export SmallWorldness to XLS file, BRAPH2 had no response, and MATLAB reported an error.

**To Reproduce**
1. Go to 'Pipeline Structural Comparison BUT'
2. Click on 'Compare Groups'
3. Right click on 'SmallWorkness' after its calculation is done, and select 'Data Selected Measures'
4. Right click on the calculation results, and select 'Export to XLS'
5. See error

**Screenshots**
![image](https://github.com/braph-software/BRAPH-2/assets/13150510/4a6f6696-bb43-4216-9d6f-05f17485038a)

**Desktop (please complete the following information):**
 - OS:  CentOS 7
 - MATLAB R2023a
 - BRAPH2 Version 2.0 build 4

**Comment by egolol** [comment]
Hi @zhileixu,
Thank you for using BRAPH 2. Could you please try again with the new build 6? The build version you are using is discontinued, we made an entirely new version on build 6. Contact us again if the problem persists. You can find help at https://github.com/braph-software/BRAPH-2/tree/develop/tutorials  and please use the discussion section for questions https://github.com/braph-software/BRAPH-2/discussions
