### ISSUE TITLE
Values of connectivity matrix (DWI - streamlines)

### ISSUE THREAD

**Issue by karl-koschutnig** [softmatterlab/BRAPH-2-Matlab#1727]
Dear Braph-experts,

First of all, thank you very much for this great tool!

I have a very basic question. We would like to explore some graph-metrics based on DWI-data. For this, we used DSI-Studio to export several different connectivity matrices. One very interesting metric concern the number of streamlines (so, how many streamlines connect each region with each other region). Here is my question: Is it possible to use this kind of data, or do I have to rescale the number of streamlines. In the documentation I only found examples with values between 0 and 1. 

Thanks a lot, 
best Karl

**Comment by iok-ui** [comment]
Hi Karl,

Thank you for using BRAPH 2!

Yes, it is possible to use connectivity data based on the number of streamlines, as long as the data is formatted in the same way as the example datasets. Whether you need to rescale the number of streamlines depends on the configuration of your study. BRAPH 2 offers several rules to help with these configurations, such as the SYMMETRIZATION RULE, NEGATIVE EDGE RULE, and NORMALIZATION RULE. In your case, the NORMALIZATION RULE ensures that all weights in the graph's adjacency matrix are scaled between 0 and 1.

For further details, please refer to Figure 7 in the following tutorial:
[FUN  Tutorial.](https://github.com/braph-software/BRAPH-2/tree/develop/tutorials/pipelines/tut_a_con_but)

Thank you again for choosing BRAPH 2! Feel free to reach out if you have any additional questions.

Best regards,
Yu-Wei

**Comment by iok-ui** [comment]
Hi Karl,

For now, I will close this issue.
Please feel free to reopen the issue if the problem persists or you still have questions.
Please also feel free to come back to us if you have any further questions or problems. 

Best,
Yu-Wei
