### ISSUE TITLE
Genesis on Apple Silicon

### ISSUE THREAD

**Issue by karl-koschutnig** [softmatterlab/BRAPH-2-Matlab#1728]
Hello,

I am using braph2 under MacOS (14.6.1) with the Apple silicon version of Matlab. It is an iMac (M1) not super fast, but OK. 
Problem is that the genesis of braph2 takes ages. Do you have any explanation for this:

**Its compilation has taken 8334.5s**

Followed by testing:

**The test has taken 16217.9s**

PS: I had the same issues with a M3pro Processor

**Comment by iok-ui** [comment]
Hi Karl,

Thank you for sharing the details regarding the long duration of the genesis and unit-test processes. If you are seeing the message confirming the successful completion of these processes (e.g., All good!), then everything is functioning as expected.

The duration of these processes is within the normal range, as you can refer to this PR where I show mine: https://github.com/braph-software/BRAPH-2/pull/1720

For stable releases, which will come in a few weeks, we will provide a pre-compiled version of BRAPH 2, which comes ready for use without needing to run these processes again.

Thank you for your patience, and please let us know if you encounter any further issues.

Best regards,
Yu-Wei

**Comment by iok-ui** [comment]
Hi Karl,

For now, I will close this issue.
Please feel free to reopen the issue if the problem persists or you still have questions.
Please also feel free to come back to us if you have any further questions or problems. 

Best,
Yu-Wei
