### ISSUE TITLE
Demonstration for BRAPH-2 Manuscript 

### ISSUE THREAD

**Issue by iok-ui** [softmatterlab/BRAPH-2-Matlab#1745]
This request needs developers of BRAPH-2 to check carefully the calculated b2 files of the demonstration pipelines for BRAPH-2 manuscript (pwd _braph2_), including

- [x] CON Community: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/EZZ3XEJqKiBFiGDAGX03QnUBVZew7kl6AXol1q3gNKIHAw?e=v0fjK0)
- [x] FUN Community: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/Ec9d5KCjhQ9DgtISAUAn6yMBQsG-Y5UOPZxcsFPbgF0RpQ?e=CIEMbr)
- [x] CON Core-Periphery: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/EXIczRJkYg5AiqXTuAGtV5UBbaBmZHn_AF4RtIVKSbMyiA?e=Vu1Bn7)
- [x] FUN Core-Periphery: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/EZFJP8Ek1pdJo9kXiNhkcrcBx7DFnBbb4YAX5EWT8TkF-g?e=pN26fK)
- [x] CON NN Classification: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/EToEEi6vw5hIuw3YdthmmMoBmusySUnsUorhgHMZACaNmQ?e=JOFgDY)
- [x] FUN NN Classification: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/EfoH_JpGnXFJkyY77r4hvskBvZTcIDl0-I4rcMnnnFstVA?e=6iu0eN)
- [x] CON-FUN MultiplexCommunity: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/EeYzCX30LXBMofIXKmNuaLEBHvlW14QUxfd9s8OmJ71PvQ?e=OLGIxE)
- [x] CON-FUN MultiplexCorePeriphery: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/EWK0RpmX-CBBvIQoHiyplPQBV-uM9PG5jt5gAwhbR-q8iA?e=ZH25yZ)
- [x] CON-FUN NN Classification: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/EfawvC02_-5LrvSJvI3LV3gBW_zYbp-6iMWB2eGkmWE1hQ?e=ftGauc)

The above-mentioned b2 files can opened and checked with develop commit 0737fbc325cef2b25d743d6042f3082b58b1ba72 (or after), using the following codes:
`%% Load as example the CON CorePeriphery pipeline`
`pipeline = Element.load('pipeline_CorePeriphery_CON.b2');`
`gui = GUIElement('PE', pipeline);`
`gui.get('DRAW');`
`gui.get('SHOW')`

The check including the following:

- [All] Open the b2 file with GUI
- [All] Open the _Analysis_ and check if the measure is calculated
- [GraphMeasure] Open the _Comparison_ and check if the comparison is calculated
- [GraphMeasure] Open the _Comparison Visualization on Brain Surface_ for the calculated comparison with FDR correction.
- [NeuralNetworks] Open the _Cross-Validation_ and check if the confusion matrix and auc are calculated
- [NeuralNetworks] Open the _Feature Importance Visualization on Brain Surface_

**Comment by bzufiriaki** [comment]
- [x] CON Community: 
- Checked that measure is calculated and plotted ("Data Selected Measures", "Plot Selected Measures" and "Plot Selected Measures on Brain")
- [x] FUN Community: 
- Checked that measure is calculated and plotted ("Data Selected Measures", "Plot Selected Measures" and "Plot Selected Measures on Brain")
- [x] CON Core-Periphery: 
- Checked that measure is calculated and plotted on individual groups ("Data Selected Measures", "Plot Selected Measures" and "Plot Selected Measures on Brain")
- Checked that comparison is calculated and plotted ("Data Selected Comparison", "Plot Selected Comparison" and "Plot Selected Comparison on Brain" (with FDR on and off))
- [x] FUN Core-Periphery: Checked that measure is calculated and plotted ("Data Selected Measures", "Plot Selected Measures" and "Plot Selected Measures on Brain")
- Checked that measure is calculated and plotted on individual groups ("Data Selected Measures", "Plot Selected Measures" and "Plot Selected Measures on Brain")
- Checked that comparison is calculated and plotted ("Data Selected Comparison", "Plot Selected Comparison" and "Plot Selected Comparison on Brain" (with FDR on and off))
- [x] CON NN Classification
- Cross-Validation (AUC and confusion matrix)
- Feature Importance Visualization on Brain Surface
- [x] FUN NN Classification
- Cross-Validation (AUC and confusion matrix)
- Feature Importance Visualization on Brain Surface
- [x] CON-FUN MultiplexCommunity
- Checked that the two measures (Multilayer Community Structure and Multilayer Modularity) are calculated and plotted ("Data Selected Measures", "Plot Selected Measures", "Plot Selected Measures on Brain", "Data Graph" and "Plot Graph Plot" (with FDR on and off))
- [x] CON-FUN MultiplexCorePeriphery
- Checked that the two measures (Multiplex Core Periphery) are calculated and plotted ("Data Selected Measures", "Plot Selected Measures", "Plot Selected Measures on Brain", "Data Graph" and "Plot Graph Plot" (with FDR on and off))
- [x] CON-FUN NN Classification
- Checked that measures (Multiplex Core Periphery, Multiplex Clustering, Multiplex Participation and Overlapping Degree) are calculated and plotted ("Data Selected Measures", "Plot Selected Measures" and "Plot Selected Measures on Brain")
- Cross-Validation (AUC and confusion matrix)
- Feature Importance Visualization on Brain Surface

**Comment by iok-ui** [comment]
An improvement reported by @bzufiriaki 
- The ROC curve plot should show when opening the plot figure panel
![image](https://github.com/user-attachments/assets/3c5091fd-fcf8-49fd-a185-f113aa197283)

Now it shows nothing and can be resolved by untoggling and toggling again the line icon button
![image](https://github.com/user-attachments/assets/9b214c3b-7867-4390-8f1b-c196a184a060)

**Comment by iok-ui** [comment]
An improvement reported by @JiaweiSun0512 
- It takes long time to recalculate the confusion matrix

**Comment by JiaweiSun0512** [comment]
> This request needs developers of BRAPH-2 to check carefully the calculated b2 files of the demonstration pipelines for BRAPH-2 manuscript, including
> 
> * [x]  CON Community: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/EZZ3XEJqKiBFiGDAGX03QnUBVZew7kl6AXol1q3gNKIHAw?e=v0fjK0)
> * [x]  FUN Community: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/Ec9d5KCjhQ9DgtISAUAn6yMBQsG-Y5UOPZxcsFPbgF0RpQ?e=CIEMbr)
> * [x]  CON Core-Periphery: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/EXIczRJkYg5AiqXTuAGtV5UBbaBmZHn_AF4RtIVKSbMyiA?e=Vu1Bn7)
> * [x]  FUN Core-Periphery: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/EZFJP8Ek1pdJo9kXiNhkcrcBx7DFnBbb4YAX5EWT8TkF-g?e=pN26fK)
> * [x]  CON NN Classification: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/EToEEi6vw5hIuw3YdthmmMoBmusySUnsUorhgHMZACaNmQ?e=JOFgDY)
> * [x]  FUN NN Classification: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/EfoH_JpGnXFJkyY77r4hvskBvZTcIDl0-I4rcMnnnFstVA?e=6iu0eN)
> * [x]  CON-FUN MultiplexCommunity: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/EeYzCX30LXBMofIXKmNuaLEBHvlW14QUxfd9s8OmJ71PvQ?e=OLGIxE)
> * [x]  CON-FUN MultiplexCorePeriphery: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/EWK0RpmX-CBBvIQoHiyplPQBV-uM9PG5jt5gAwhbR-q8iA?e=ZH25yZ)
> * [x]  CON-FUN NN Classification: [LINK](https://gunet-my.sharepoint.com/:u:/g/personal/yu-wei_chang_gu_se/EfawvC02_-5LrvSJvI3LV3gBW_zYbp-6iMWB2eGkmWE1hQ?e=ftGauc)
> 
> The above-mentioned b2 files can opened and checked with develop commit [0737fbc](https://github.com/braph-software/BRAPH-2/commit/0737fbc325cef2b25d743d6042f3082b58b1ba72) (or after), using the following codes: `%% Load as example the CON CorePeriphery pipeline` `pipeline = Element.load('pipeline_CorePeriphery_CON.b2');` `gui = GUIElement('PE', pipeline);` `gui.get('DRAW');` `gui.get('SHOW')`
> 
> The check including the following:
> 
> * [All] Open the b2 file with GUI
> * [All] Open the _Analysis_ and check if the measure is calculated
> * [GraphMeasure] Open the _Comparison_ and check if the comparison is calculated
> * [GraphMeasure] Open the _Comparison Visualization on Brain Surface_ for the calculated comparison with FDR correction.
> * [NeuralNetworks] Open the _Cross-Validation_ and check if the confusion matrix and auc are calculated
> * [NeuralNetworks] Open the _Feature Importance Visualization on Brain Surface_
